FROM node:14-alpine AS builder
WORKDIR /opt/app
COPY . .
RUN npm install
ENV NODE_ENV production
RUN npm run build && \
    npm run export

FROM nginx:alpine
COPY --from=builder /opt/app/out /usr/share/nginx/html
RUN sed -i 's/index  index.html index.htm;/try_files $uri $uri\/ \/index.html;/g' /etc/nginx/conf.d/default.conf 
